version: '3'

services:
    balancer:
        image: 'nginx:latest'
        ports:
          - 80:80
        volumes:
          - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    web-1:
        image: 'php:7.3-apache'
        volumes:
            - ./website/:/var/www/html/
    web-2:
        image: 'php:7.3-apache'
        volumes:
            - ./website/:/var/www/html/
