version: '3'

services:
    balancer:
        image: 'haproxy:latest'
        ports:
          - 80:80
          - 8404:8404
        volumes:
          - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    web-1:
        image: 'php:7.3-apache'
        volumes:
            - ./website/:/var/www/html/
    web-2:
        image: 'php:7.3-apache'
        volumes:
            - ./website/:/var/www/html/
