version: '3'

services:
    website:
        build:
            context: .
            dockerfile: Dockerfile.apache
        ports:
            - 80:80
        volumes:
            - ./website/:/var/www/html/
            - ${PWD}/apache2.conf:/etc/apache2/apache2.conf