version: '3'

services:
    balancer:
        image: 'haproxy:latest'
        ports:
          - 80:80
          - 8404:8404
        volumes:
          - ${PWD}/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg

    web-one:
        image: 'php:7.3-apache'
        ports:
            - 5000:80
        volumes:
            - ./website/:/var/www/html/

    web-two:
        image: 'php:7.3-apache'
        ports:
            - 5001:80
        volumes:
            - ./website/:/var/www/html/

    zabbix-web:
        image: 'zabbix/zabbix-web-nginx-pgsql:alpine-latest'
        ports:
            - 8080:8080
        environment:
            DB_SERVER_HOST: postgres
            POSTGRES_USER: xhajekm
            POSTGRES_PASSWORD: top-secret
            ZBX_SERVER_HOST: zabbix-server
            PHP_TZ: Europe/Bratislava
            
    zabbix-server:
        image: 'zabbix/zabbix-server-pgsql:alpine-latest'
        environment: 
            DB_SERVER_HOST: postgres
            POSTGRES_USER: xhajekm
            POSTGRES_PASSWORD: top-secret
        
    postgres:
        image: 'postgres:12-alpine'
        restart: always
        environment:
            POSTGRES_USER: xhajekm
            POSTGRES_PASSWORD: top-secret
        volumes:
            - pgsql:/var/lib/postgresql/data
            
volumes:
    pgsql:
