version: '3'

services:
    zabbix-agent:   # Monitoring nginx with zabbix
        image: 'zabbix/zabbix-agent:alpine-latest'
        environment:
            ZBX_HOSTNAME: zabbix-agent
            ZBX_SERVER_HOST: zabbix-server

    zabbix-web:
        image: 'zabbix/zabbix-web-nginx-pgsql:alpine-latest'
        ports:
            - 8080:8080
        environment:    # Do env súboru
            DB_SERVER_HOST: postgres
            POSTGRES_USER: xhajekm
            POSTGRES_PASSWORD: top-secret
            ZBX_SERVER_HOST: zabbix-server
            PHP_TZ: Europe/Bratislava
            
    zabbix-server:
        image: 'zabbix/zabbix-server-pgsql:alpine-latest'
        environment: 
            DB_SERVER_HOST: postgres
            POSTGRES_USER: xhajekm
            POSTGRES_PASSWORD: top-secret
        
    postgres:
        image: 'postgres:12-alpine'
        restart: always
        environment:
            POSTGRES_USER: xhajekm
            POSTGRES_PASSWORD: top-secret
        volumes:
            - pgsql:/var/lib/postgresql/data
            
volumes:
    pgsql:
